### ISSUE TITLE
Example and Screen Shots Please

### ISSUE THREAD

**Issue by deresegetachew** [bringnow/react-native-sidebar#1]

**Comment by ahmed1490** [comment]
+1

**Comment by egeese** [comment]
Example/Screenshots will follow, Sorry for delay.

**Comment by ahmed1490** [comment]
no worries. A gif would be cool!

**Comment by jordanbrown** [comment]
+1

**Comment by filipef101** [comment]
please

**Comment by prateekpareekvyas** [comment]
+1

**Comment by christoph-jerolimov** [comment]
Project and ticket is not updated in the last 5 years. Closing this ticket, I don't know if I will ever find the time to solve this or test this lib with latest RN.
