### ISSUE TITLE
open function for right side broken?

### ISSUE THREAD

**Issue by jonegerton** [bringnow/react-native-sidebar#3]
Is `this.props.rightSidebar && side !== 'right'` correct in the line below? Would expect `=== 'right'` on that line instead of `!== 'right'`

    open(side) {
        if (this.props.leftSidebar && side !== 'right') {
            this.openLeftSidebar();
        } else if (this.props.rightSidebar && side !== 'right') {
            this.openRightSidebar();
        } else {
            this.close();
        }
    }

**Comment by christoph-jerolimov** [comment]
Your right, this should be `this.props.rightSidebar && side === 'right'`. Can you open a PR?

**Comment by christoph-jerolimov** [comment]
Thanks!
